### ISSUE TITLE
Mit Contao Manager nicht installierbar

### ISSUE THREAD

**Issue by planepix** [presprog/contao-undo#1]
Hallo Benedict,

unter 4.4.8 und Contao Manager 1.0.0-beta12 wird die Erweiterung mit „Inkompatibel” gekennzeichnet und lässt sich nicht installieren. Mit Konsole klappt die Installation.

Beste Grüße
Thomas

**Comment by bezin** [comment]
Danke für den Hinweis, der Fix kommt :)

**Comment by bezin** [comment]
Könntest du es bitte noch einmal mit dem Manager testen?

**Comment by planepix** [comment]
Wird immer noch als Inkompatibel angezeigt. Hatte die via Konsole installierte gelöscht und den Cache neu aufgebaut.

**Comment by bezin** [comment]
Bei mir lief es gerade über den Manager problemlos durch. Eventuell war bei dir die neue Version noch nicht überall verfügbar. Versuche es bitte noch einmal, falls du Zeit hast – eventuell auch explizit mit Versionsnummer 0.1.1.

**Comment by planepix** [comment]
Jetzt wurde es als kompatibel angezeigt und lies sich installieren. Ich war vorher vermutlich zu schnell ;-)
Danke.

**Comment by bezin** [comment]
Wunderbar, danke dir für das Feedback!
